services:
  auth:
    build:
      context: .
      dockerfile: ./apps/auth/Dockerfile
      target: development
    command: pnpm run start:dev auth
    env_file:
      - ./apps/auth/.env
    ports:
      - '3000:3000'
    volumes:
      - .:/usr/src/app
  articles:
    build:
      context: .
      dockerfile: ./apps/articles/Dockerfile
      target: development
    command: pnpm run start:dev articles
    env_file:
      - ./apps/articles/.env
    ports:
      - '3001:3001'
    volumes:
      - .:/usr/src/app
  mongo:
    image: mongo
  rabbitmq:
    image: rabbitmq
    ports:
      - 5672:5672
